import { useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { useSpring, animated } from 'react-spring'

import Button from '../Components/Button'

import {
    UilInstagram,
    UilDribbble,
    UilArrowRight,
} from '@iconscout/react-unicons'

export default function Home() {
    const fadeShapeBottom = useSpring({
        from: {
            opacity: 0,
            transform: 'translateY(-20px)',
        },
        to: {
            opacity: 1,
            transform: 'translateY(0px)',
        },
    })

    const justFade = useSpring({
        from: {
            opacity: 0,
        },
        to: {
            opacity: 1,
        },
        delay: 200,
    })

    const fadeBottom = useSpring({
        from: {
            opacity: 0,
            transform: 'translateY(-100px)',
        },
        to: {
            opacity: 1,
            transform: 'translateY(0px)',
        },
        delay: 300,
    })

    const fadeShapeTop = useSpring({
        from: {
            opacity: 0,
            transform: 'translateY(50px)',
        },
        to: {
            opacity: 1,
            transform: 'translateY(0px)',
        },
        delay: 700,
    })

    const fadeScale = useSpring({
        from: {
            opacity: 0,
            transform: 'scale(0.1)',
        },
        to: {
            opacity: 1,
            transform: 'scale(1)',
        },
        delay: 900,
    })

    useEffect(() => {
        document.addEventListener('mousemove', parallax)

        function parallax(e) {
            document.querySelectorAll('.move-paral').forEach((layer) => {
                const speed = layer.getAttribute('data-speed')

                const x = (window.innerWidth - e.pageX * speed) / 100
                const y = (window.innerHeight - e.pageY * speed) / 100

                if (e.pageY <= window.innerHeight) {
                    layer.style.transform = `translateX(${x}px) translateY(${y}px)`
                }
            })
        }

        return () => {
            document.removeEventListener('mousemove', parallax)
        }
    }, [])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <div className="fixed top-1/2 -left-8 transform -rotate-90 flex">
                <Link href="https://instagram.com/arefeghbalidev">
                    <a target="_blank">
                        <span className="flex items-center">
                            <UilInstagram />
                            Instagram
                        </span>
                    </a>
                </Link>
                <Link href="https://dribbble.com/arefeghbali">
                    <a target="_blank" className="ml-8">
                        <span className="flex items-center">
                            <UilDribbble />
                            Dribbble
                        </span>
                    </a>
                </Link>
            </div>
            <animated.div
                className="md:container mx-auto"
                style={fadeShapeBottom}>
                <div className="flex items-center justify-between py-8">
                    <div className="flex items-center justify-start">
                        <div className="flex items-center justify-start">
                            <Image
                                src="/static/images/logo.svg"
                                alt="Logo"
                                width="34px"
                                height="34px"
                            />
                            <h4 className="ml-2">OnlineTutors</h4>
                        </div>
                        <Link href="/services">
                            <a className="hover:text-indigo-500 font-medium ml-16">
                                Services
                            </a>
                        </Link>
                        <Link href="/tutors">
                            <a className="hover:text-indigo-500 font-medium ml-8">
                                Our Tutors
                            </a>
                        </Link>
                        <Link href="/about">
                            <a className="hover:text-indigo-500 font-medium ml-8">
                                About Us
                            </a>
                        </Link>
                        <Link href="/support">
                            <a className="hover:text-indigo-500 font-medium ml-8">
                                Support
                            </a>
                        </Link>
                    </div>
                    <div className="flex items-center justify-end">
                        <Link href="/auth">
                            <a className="mr-8 hover:text-indigo-500 font-medium">
                                Join Us/Login
                            </a>
                        </Link>
                        <Button type="button" color="primary">
                            Start Learning
                        </Button>
                    </div>
                </div>
            </animated.div>
            <div className="md:container mx-auto h-screen grid grid-cols-2 gap-16 items-center justify-center">
                <div className="flex flex-col relative h-3/4 justify-center">
                    <animated.div
                        className="rounded-full w-20 h-20 bg-pink-500 absolute top-20 left-40 move-paral"
                        data-speed="-3"
                        style={fadeShapeBottom}></animated.div>
                    <animated.div
                        className="rounded-full w-10 h-10 bg-amber-500 absolute top-20 left-10 move-paral"
                        data-speed="2"
                        style={justFade}></animated.div>
                    <animated.div style={fadeScale}>
                        <h1>Online Video Tutorials For Students.</h1>
                        <p className="text-lg text-black-300 mt-2">
                            Best professional tutors to help students with their
                            lessons and push them towards graduation. With valid
                            certificates for finishing classes.
                        </p>
                        <div className="flex items-center justify-start mt-8">
                            <Button type="button" color="primary">
                                Start Learning
                            </Button>
                            <Link href="/how">
                                <a className="ml-6 py-3 px-8 rounded-full border-2 border-indigo-500 text-indigo-500 hover:bg-indigo-500 hover:text-white transition duration-200 colors">
                                    How It Works?
                                </a>
                            </Link>
                        </div>
                    </animated.div>
                    <animated.img
                        src="/static/images/BottomShape.svg"
                        alt="QCircleIndigo"
                        width="110px"
                        height="100px"
                        className="absolute bottom-0 right-1/4 move-paral"
                        style={fadeShapeTop}
                        data-speed="3"
                    />
                </div>
                <animated.div
                    className="w-full h-3/4 grid place-items-center relative"
                    style={fadeBottom}>
                    <div
                        className="rounded-full w-96 h-96 bg-indigo-500 absolute top-10 left-30 z-10 move-paral"
                        data-speed="3"></div>
                    <div
                        className="rounded-full w-64 h-64 bg-pink-500 absolute bottom-1/4 left-20 z-20 move-paral"
                        data-speed="3"></div>
                    <img
                        src="/static/images/QCircle.svg"
                        alt="QCircle"
                        width="280px"
                        height="260px"
                        className="absolute bottom-1/4 right-0 z-30 move-paral"
                        data-speed="3"
                    />
                    <img
                        src="/static/images/girl.png"
                        width="420px"
                        height="500px"
                        alt="student"
                        className="z-40"
                    />
                    <div
                        className="rounded-md bg-white shadow-md border border-black-100 px-4 py-14 absolute bottom-4 left-0 w-full z-50 move-paral"
                        data-speed="-3">
                        <h3 className="text-center text-indigo-500">
                            +2000 Hours of tutorials for all students.
                        </h3>
                    </div>
                </animated.div>
            </div>
            <div className="md:container mx-auto mt-20">
                <h2 className="text-center w-full mb-8">
                    How we help students
                </h2>
                <div className="grid grid-cols-3 items-center justify-between gap-8">
                    <div className="rounded-md shadow-md p-4 border border-black-100 pb-8">
                        <img
                            src="/static/images/onlineclass.svg"
                            alt="Online Class"
                            width="100%"
                            height="auto"
                        />
                        <h4 className="text-center">Online Classes</h4>
                        <p className="text-center text-black-300">
                            We provide online classes and video tutorials for
                            students in all subjects.
                        </p>
                        <Link href="/valid-certificate">
                            <a className="flex items-center justify-center text-center mt-4 text-amber-500">
                                Learn More
                                <UilArrowRight className="ml-2" />
                            </a>
                        </Link>
                    </div>
                    <div className="rounded-md shadow-md p-4 border border-black-100 pb-8">
                        <img
                            src="/static/images/graduation.svg"
                            alt="Graduation"
                            width="100%"
                            height="auto"
                        />
                        <h4 className="text-center">Valid Certification</h4>
                        <p className="text-center text-black-300">
                            After students pass the final tests we give them
                            valid certifications approving that they passed the
                            subjects.
                        </p>
                        <Link href="/valid-certificate">
                            <a className="flex items-center justify-center text-center mt-4 text-amber-500">
                                Learn More
                                <UilArrowRight className="ml-2" />
                            </a>
                        </Link>
                    </div>
                    <div className="rounded-md shadow-md p-4 border border-black-100 pb-8">
                        <img
                            src="/static/images/goodtutors.svg"
                            alt="Online Tutors"
                            width="100%"
                            height="auto"
                        />
                        <h4 className="text-center">Experienced Tutors</h4>
                        <p className="text-center text-black-300">
                            Our tutors are experienced teachers and can help
                            students learn any subject easily.
                        </p>
                        <Link href="/valid-certificate">
                            <a className="flex items-center justify-center text-center mt-4 text-amber-500">
                                Learn More
                                <UilArrowRight className="ml-2" />
                            </a>
                        </Link>
                    </div>
                </div>
                <div className="grid grid-cols-2 gap-8 mt-20 pb-8">
                    <div>
                        <h2>Get a personal tutor</h2>
                        <p className="text-black-300">
                            If you want more teaching for yourself or your kids
                            you can get a personal tutor and they will teach
                            your kids in more details.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}
